### ISSUE TITLE
Again visible widgets not shown in the apps

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#93] opened 2016-01-20 21:19 UTC
I have Alarm widget that is a hidden, then I make it visible. In the apps, as example in Logical Rules I can't see it, but after z-way restart I see Alarm widget in apps.

**Comment by ronie-z-wave** [comment] 2016-01-21 06:22
duplicate of #85

**Closed by ronie-z-wave** 2016-01-21 06:22 UTC
